# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_Uniform_32Bit/design_Uniform_32Bit.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_Uniform_32Bit || ORIG_REF_NAME==design_Uniform_32Bit} -quiet] -quiet

# IP: bd/design_Uniform_32Bit/ip/design_Uniform_32Bit_processing_system7_0_0/design_Uniform_32Bit_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_Uniform_32Bit_processing_system7_0_0 || ORIG_REF_NAME==design_Uniform_32Bit_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_Uniform_32Bit/ip/design_Uniform_32Bit_uniform_0_0/design_Uniform_32Bit_uniform_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_Uniform_32Bit_uniform_0_0 || ORIG_REF_NAME==design_Uniform_32Bit_uniform_0_0} -quiet] -quiet

# IP: bd/design_Uniform_32Bit/ip/design_Uniform_32Bit_ps7_0_axi_periph_0/design_Uniform_32Bit_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_Uniform_32Bit_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_Uniform_32Bit_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_Uniform_32Bit/ip/design_Uniform_32Bit_rst_ps7_0_100M_0/design_Uniform_32Bit_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_Uniform_32Bit_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_Uniform_32Bit_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/design_Uniform_32Bit/ip/design_Uniform_32Bit_auto_pc_0/design_Uniform_32Bit_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_Uniform_32Bit_auto_pc_0 || ORIG_REF_NAME==design_Uniform_32Bit_auto_pc_0} -quiet] -quiet

# XDC: bd/design_Uniform_32Bit/design_Uniform_32Bit_ooc.xdc
