# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/lpb16134/PYNQ-2.3/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_auto_pc_11/base_auto_pc_11.xci
# IP: The module: 'base_auto_pc_11' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lpb16134/PYNQ-2.3/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_auto_pc_11/base_auto_pc_11_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_auto_pc_11'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/lpb16134/PYNQ-2.3/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_auto_pc_11/base_auto_pc_11.xci
# IP: The module: 'base_auto_pc_11' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lpb16134/PYNQ-2.3/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_auto_pc_11/base_auto_pc_11_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_auto_pc_11'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
